### ISSUE TITLE
Error following directions in /shells/8.2.0/getting-started.html "Creating the Shell Project"

### ISSUE THREAD

**Issue by Kirizan** [QualiSystems/devguide_source#161]
After following the directions in the guide, I get the following error when attempting to create a new shell. This is shellfoundry version 1.1.9 in Windows Server 2012 R2 standard.

shellfoundry new linux-server-shell
Unexpected error during shellfoundry version check. Error: .
Traceback (most recent call last):
  File "C:\Python27\Scripts\shellfoundry-script.py", line 11, in <module>
    load_entry_point('shellfoundry==1.1.9', 'console_scripts', 'shellfoundry')()

  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\shellfoundry\decorators\version_check.py",
 line 23, in decorator
    is_greater_version, is_major_release = is_index_version_greater_than_current
()
  File "c:\python27\lib\site-packages\shellfoundry\utilities\__init__.py", line
41, in is_index_version_greater_than_current
    is_greater_version = index > installed
  File "c:\python27\lib\distutils\version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'

**Comment by TomerAdmon** [comment]
Hi @Kirizan, 
Do you still get errors while installing ShellFoundry?
The Shellfoundry project is managed in other repo where you can report a bug in and the developers will help you.
http://github.com/QualiSystems/shellfoundry

Tomer

**Comment by Shnitselon** [comment]
if problem persists, please open under shellfoundry repo
